### PR TITLE
Adding support for reversible female USB Port and optional reset switch.

### PR DESCRIPTION
**Pull request by profet23**
This will allow the right hand of the Ergodox to be flipped and used as the left hand. In this scenario, the teensy should be soldered with its bottom facing up on the top of the left hand PCB. Because doing this obscures the teensy mounted reset button, I have added pads for an optional reset switch that can be used from the bottom of a left hand only Ergodox.

Reset switch part number: OMRON B3U-1000P

This change will allow ergodox gamepads without requiring a custom case (although you probably want to cut a reset hole in the bottom plate for the optional reset switch).

### CODE REVIEW

**Comment by robotmaxtron** [comment]
This is outstanding, thank you @profet23 

I'll review the pcb a bit more before I merge it and will write up something as a variant to the main documentation or something soon.

**Comment by robotmaxtron** [comment]
@arij Would you mind taking a look at this as well?

**Comment by robotmaxtron** [comment]
The only thing that stands out to me as a little odd is that the pin 16 RST seems like it's not connected to anything.

pin

**Comment by profet23** [comment]
The pin is for the currently unused reset pin on the Teensy 2.0 

It would only be required if you wanted to use the optional reset switch that is also added in the pull request. 

The bigger thing I would like reviewed are the changes to the USB port wiring.

**Comment by profet23** [comment]
I have produced this version of the PCB and wired up a standard version of the ErgoDox using it. It works flawlessly and is now for sale in my web shop.

Next step is to wire up a left handed version and confirm that the changes allow gamepad support. I'll do that this week.

**Comment by robotmaxtron** [comment]
@profet23 Any progress on the new PCB for left hand working as a gamepad?

**Comment by profet23** [comment]
Finally got around to building one of these.  Everything is confirmed working:  http://imgur.com/a/zog7Z

**Comment by profet23** [comment]
ping

**Comment by profet23** [comment]
@robotmaxtron any info on merging this?

**Comment by robotmaxtron** [comment]
@profet23 Hey sorry, I've been super busy. I've gone ahead and merged it in. Thanks a bunch for all the work on this.

**Pull request merged**
